" Miselaneous settings
set nocompatible      " Do not run in vim compatability mode
set shortmess+=I      " Disable start screen

" Display Settings
syntax enable         " Enable syntax highlighting
set number            " Show line numbers
set relativenumber    " Show relative numbers
set scrolloff=5       " Minimum number of lines kept above and below the cursor
set nowrap            " Disable line wrapping
set colorcolumn=80    " Draw line at this character limit
set encoding=utf-8    " Enable UTF-8 character encoding
set laststatus=2      " Always show the status bar at the botom
set showtabline=2     " Always show the tab bar at the top

" Spaces and tabs
set expandtab         " Expand tab character to spaces when <Tab> is pressed
set shiftwidth=4      " Number of spaces added automatically or when indenting
set softtabstop=4     " Width of Tab character in insertion mode
set autoindent        " Copy indent from current line when starting new line
set cindent           " Like `smartindent` but more syntax-aware

" Buffer settings
set tabpagemax=50     " Maximum number of tabs to be opened with `vim -p ...`
set noswapfile        " Open new buffers without creating a temporary swap file

" Keyboard mappings
let mapleader=","               " Remap <Leader> to ,
nnoremap <CR> :noh<CR><CR>      " Clear search highlight with <Return>
nnoremap tl :tabnext<CR>        " Tab next with tl
nnoremap th :tabprev<CR>        " Tab prev with th
map <C-j> :set paste<CR>        " Set paste with <Control>j
map <C-k> :set nopaste<CR>      " Set nopaste with <Control>k
inoremap {<CR> {<CR>}<Esc><S-o> " Auto-close and indent after opening {

" Filetype overrides
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Colorscheme settings
set background=dark
colorscheme base16-tomorrow
highlight TrailingWhitespace ctermbg=darkred guibg=darkred
match TrailingWhitespace /\s\+$/

" Colorscheme overrides
hi Search       ctermfg=00 ctermbg=03
hi LineNr       ctermfg=12 ctermbg=00
hi CursorLineNr ctermfg=03 ctermbg=00
hi SpellBad     ctermfg=01 ctermbg=00
hi SpellLocal   ctermfg=01 ctermbg=00
hi SpellCap     ctermfg=01 ctermbg=00
hi SpellRare    ctermfg=01 ctermbg=00
hi Todo         ctermfg=01 ctermbg=00
hi TabLineSel   ctermfg=03 ctermbg=00
hi StatusLine   ctermfg=07 ctermbg=10
hi StatusLineNC ctermfg=07 ctermbg=00
hi ColorColumn  ctermfg=01 ctermbg=10
